name: publish
on:
  push:
    branches:
      - 'main'
# env:
#   PUBLISH_VERSION: ${{github.ref_name}}
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: init
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@gmail.com"
      - uses: actions/checkout@v4
      - name: install-node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - id: publish
        name: publish
        uses: JS-DevTools/npm-publish@v3.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/package.json
      - if: steps.publish.outputs.old-version != steps.publish.outputs.version
        run: |
          echo "[${{ steps.publish.outputs.type }}]Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}✔️"
          git tag v${{steps.publish.outputs.version}}
          git push origin v${{steps.publish.outputs.version}}